// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkIY93WGlOZYMbqBhFRwZs7t2NcO5soW4',
    appId: '1:379461142898:web:5f0fef0b3e997a953a35eb',
    messagingSenderId: '379461142898',
    projectId: 'reelity-app',
    authDomain: 'reelity-app.firebaseapp.com',
    storageBucket: 'reelity-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMF3NMXWKkDWalApMtjS012O5BwhzpjK0',
    appId: '1:379461142898:android:cda9501fb305f8603a35eb',
    messagingSenderId: '379461142898',
    projectId: 'reelity-app',
    storageBucket: 'reelity-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfMMLOnYlpnAyX9SJCLueJGf7wxDTl39I',
    appId: '1:379461142898:ios:28e87b51d006d0533a35eb',
    messagingSenderId: '379461142898',
    projectId: 'reelity-app',
    storageBucket: 'reelity-app.firebasestorage.app',
    iosBundleId: 'com.example.reelity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfMMLOnYlpnAyX9SJCLueJGf7wxDTl39I',
    appId: '1:379461142898:ios:28e87b51d006d0533a35eb',
    messagingSenderId: '379461142898',
    projectId: 'reelity-app',
    storageBucket: 'reelity-app.firebasestorage.app',
    iosBundleId: 'com.example.reelity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkIY93WGlOZYMbqBhFRwZs7t2NcO5soW4',
    appId: '1:379461142898:web:b5b2c4fbe098d1f93a35eb',
    messagingSenderId: '379461142898',
    projectId: 'reelity-app',
    authDomain: 'reelity-app.firebaseapp.com',
    storageBucket: 'reelity-app.firebasestorage.app',
  );
}
